"""Orchestrator: AgentIR + topology → deterministic {relpath: content} file map."""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from .ir import AgentIR
from .loader import load_agent
from .dispatch import Topology, dispatch
from .validator import build_blockers
from .hitl_map import map_hitl, HitlMapping
from .graphplan import plan_dag_graph, DagPlan
from .render import render
from .writer import write_zip, write_dir


@dataclass
class GenerateResult:
    agent: AgentIR
    topology: Topology
    blockers: dict[str, Any]
    files: dict[str, str] = field(default_factory=dict)

    @property
    def tree(self) -> list[str]:
        return sorted(self.files)

    def zip_bytes(self) -> bytes:
        return write_zip(self.files, root=self.agent.slug)

    def write(self, out_dir):
        return write_dir(self.files, out_dir)


def _node_names(agent: AgentIR, topo: Topology, plan: DagPlan | None) -> set[str]:
    if topo is Topology.SUPERVISOR:
        return {"supervisor"} | {sa.name for sa in agent.sub_agents}
    if topo is Topology.PIPELINE:
        return {sa.name for sa in agent.sub_agents}
    if topo is Topology.PARALLEL:
        return {sa.name for sa in agent.sub_agents} | {"aggregate"}
    if topo is Topology.DAG:
        if plan is not None:
            return {nid for nid, _ in plan.nodes}
        return {"retrieve", "generate"} if agent.rag.enabled else {"agent", "tools"}
    return {"agent", "tools"}  # single (ReAct)


def _expected_nodes(agent: AgentIR, topo: Topology, plan: DagPlan | None) -> list[str]:
    if topo is Topology.SUPERVISOR:
        return sorted({sa.name for sa in agent.sub_agents} | {"supervisor"})
    if topo is Topology.PIPELINE:
        return [sa.name for sa in agent.sub_agents]  # config order (semantic)
    if topo is Topology.PARALLEL:
        return sorted({sa.name for sa in agent.sub_agents} | {"aggregate"})
    if topo is Topology.DAG and plan is not None:
        return [nid for nid, _ in plan.nodes]  # spec order (semantic)
    if topo is Topology.DAG and agent.rag.enabled:
        return ["generate", "retrieve"]
    return ["agent"]


def generate(source: str | dict | AgentIR, *, llm_target: str = "aistudio") -> GenerateResult:
    agent = source if isinstance(source, AgentIR) else load_agent(source, llm_target=llm_target)
    topo = dispatch(agent)
    blockers = build_blockers(agent)

    # explicit DAG plan (only when a graph spec is present); shared with runtime.py
    dag_plan = (plan_dag_graph(agent.graph, has_tools=bool(agent.tools))
                if topo is Topology.DAG and agent.graph is not None and agent.graph.nodes else None)

    node_names = _node_names(agent, topo, dag_plan)
    hitl: HitlMapping = map_hitl(agent.hitl, node_names)
    expected_nodes = _expected_nodes(agent, topo, dag_plan)

    needs_ddgs = any(t.capability == "web_search" for t in agent.tools)
    secret_names = sorted(set(agent.secret_refs.values()))  # names only, deterministic order
    ctx = dict(
        agent=agent, topology=topo.value, model=agent.model, prompt=agent.prompt,
        tools=agent.tools, disabled_tools=agent.disabled_tools, sub_agents=agent.sub_agents,
        rag=agent.rag, hitl=hitl, blockers=blockers, expected_nodes=expected_nodes, dag_plan=dag_plan,
        pkg=agent.pkg, aistudio=(agent.llm_target != "vertex"), vertex=(agent.llm_target == "vertex"),
        needs_ddgs=needs_ddgs, secret_names=secret_names,
    )

    pkg = agent.pkg
    files: dict[str, str] = {}

    # ---- project root ----
    files["pyproject.toml"] = render("_base/pyproject.toml.j2", **ctx)
    files["requirements.txt"] = render("_base/requirements.txt.j2", **ctx)
    files["README.md"] = render("_base/README.md.j2", **ctx)
    files[".env.example"] = render("_base/env.example.j2", **ctx)
    files[".gitignore"] = ".venv/\n__pycache__/\n*.pyc\n.env\nchroma_db/\n.pytest_cache/\n"
    files["config/agent.config.json"] = json.dumps(agent.raw_config, indent=2, sort_keys=True) + "\n"

    # ---- package ----
    base = f"src/{pkg}"
    files[f"{base}/__init__.py"] = f'"""{agent.name} — generated by agent_forge."""\n'
    files[f"{base}/model.py"] = render("_base/model.py.j2", **ctx)
    files[f"{base}/prompts.py"] = render("_base/prompts.py.j2", **ctx)
    files[f"{base}/tools.py"] = render("tools.py.j2", **ctx)
    files[f"{base}/memory.py"] = render("_base/memory.py.j2", **ctx)
    files[f"{base}/graph.py"] = render(f"{topo.value}/graph.py.j2", **ctx)

    # ---- runtime ----
    files[f"{base}/runtime/__init__.py"] = ""
    files[f"{base}/runtime/cli.py"] = render("_base/runtime_cli.py.j2", **ctx)
    files[f"{base}/runtime/server.py"] = render("_base/runtime_server.py.j2", **ctx)

    # ---- RAG (Phase 4) ----
    if agent.rag.enabled:
        files[f"{base}/rag/__init__.py"] = ""
        files[f"{base}/rag/retriever.py"] = render("rag/retriever.py.j2", **ctx)
        files[f"{base}/rag/ingest.py"] = render("rag/ingest.py.j2", **ctx)
        for i, doc in enumerate(_sample_docs(agent)):
            files[f"{base}/rag/sample_docs/{doc['doc_id']}.md"] = doc["text"] + "\n"

    # ---- tests ---- (root conftest puts src/ on sys.path; no tests/__init__.py)
    files["conftest.py"] = (
        "import sys, pathlib\n"
        "sys.path.insert(0, str(pathlib.Path(__file__).parent / 'src'))\n"
    )
    files["tests/_fakes.py"] = render("_base/tests_fakes.py.j2", **ctx)
    files["tests/test_compiles.py"] = render("_base/tests_compiles.py.j2", **ctx)
    files["tests/test_advisory_guard.py"] = render("_base/tests_advisory_guard.py.j2", **ctx)

    return GenerateResult(agent=agent, topology=topo, blockers=blockers, files=files)


def _sample_docs(agent: AgentIR) -> list[dict[str, str]]:
    """Seed docs for the local vector store: use bundled snippets if the service
    passed them, else a deterministic placeholder derived from the objective."""
    if agent.rag.snippets:
        return [{"doc_id": s.get("doc_id", f"DOC-{i}"), "text": s.get("text", "")}
                for i, s in enumerate(agent.rag.snippets)]
    return [{
        "doc_id": "SAMPLE-0001",
        "text": (f"# Sample knowledge for {agent.name}\n\n"
                 f"Replace this with real documents. Objective: {agent.objective}\n\n"
                 f"Knowledge sources referenced: {', '.join(agent.rag.knowledge_source_refs) or '(none)'}."),
    }]
