"""Model factory — Google AI Studio (Gemini).

Generated by agent_forge from model_primary="gemini-1.5-pro"
(temperature=0.3, max_output_tokens=4096).
"""
import os
from langchain_google_genai import ChatGoogleGenerativeAI

_PRIMARY = "gemini-1.5-pro"
_FALLBACK = "gemini-1.5-pro"
_TEMPERATURE = 0.3
_MAX_TOKENS = 4096
_RETRIES = 2


def has_credentials() -> bool:
    """True when runtime credentials are present (so we can build the real model)."""
    return bool(os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY"))


def _make(model_id: str):
    return ChatGoogleGenerativeAI(model=model_id, temperature=_TEMPERATURE, max_output_tokens=_MAX_TOKENS)


def build_model():
    """Primary Gemini model with retry and an optional fallback model."""
    model = _make(os.getenv("MODEL", _PRIMARY)).with_retry(stop_after_attempt=_RETRIES + 1)
    if _FALLBACK:
        model = model.with_fallbacks([_make(_FALLBACK)])
    return model
